import "./globals.css";
import type { ReactNode } from "react";
import Header from "../components/Header";

interface PropTypes {
  children: ReactNode;
}

export default function RootLayout({ children }: PropTypes) {
  return (
    <html lang="en">
      <head>
        <title>Computech — Welcome to Computech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-gray-50">
        <Header />
        {children}
      </body>
    </html>
  );
}
